networks:
    docker-network:
        name: docker-network
        driver: bridge

#==============================================

volumes:
    wp:
        driver: local
        name: wp
        driver_opts:
            type: none
            o: bind
            device: ${VOLUME_PATH}/wordpress
  
    db:
        driver: local
        name: db
        driver_opts:
            type: none
            o: bind
            device: ${VOLUME_PATH}/mariadb

#==============================================

services:
    
    mariadb:
        restart: on-failure
        container_name: mariadb
        build: ./requirements/mariadb
        image: mariadb:inception
        env_file:
            - .env
        volumes:
            - db:/var/lib/mysql
        networks:
            - docker-network
        

    wordpress:
        restart: on-failure
        container_name: wordpress
        build: ./requirements/wordpress
        image: wordpress:inception
        env_file:
            - .env
        depends_on:
            - mariadb
        volumes:
            - wp:/var/www/html
        networks:
            - docker-network

    nginx:
        restart: on-failure
        container_name: nginx
        build: ./requirements/nginx
        image: nginx:inception
        env_file:
            - .env
        ports:
            - "443:443"
        depends_on:
            - wordpress
        volumes:
            - wp:/var/www/html
        networks:
            - docker-network